### ISSUE TITLE
Ошибка при запуске приложения на СУБД PostgreSQL

### ISSUE THREAD

**Issue by victoria6991** [victoria6991/postgres#1]
**Предусловия:**
Установлен Docker.

**Шаги:**
1. Создать Gradle-проект
2. Добавить файл .gitignore
3. Вставить jar-файл в корень проекта
4. Создать файл docker-compose.yml (прописать нужную сборку postgres, биндинг портов, volumes, переменное окружение)
5. Создать файл application.properties и прописать использованные ранее параметры
6. Запустить контейнер из консоли командой docker-compose up
7. Запустить jar-ник из консоли командой java -jar db-api.jar

**Ожидаемый результат:**
На странице http://localhost:9999/ открывается JSON с картами

**Фактический результат:**
На странице http://localhost:9999/ открывается Whitelabel Error Page
[Скриншот окна ошибки](https://ibb.co/vxm7hBL)

Окружение: Windows 10 21H2 64-разрядная, сборка 19044.1706, Java 11, [репо на GitHub](https://github.com/victoria6991/postgres.git)

Логи:
[Консоль запуска контейнера](https://ibb.co/HPhVywj)
[Логи контейнера из Serviсes](https://ibb.co/xgnFCbN)
[Логи из консоли после запуска jar-ника](https://ibb.co/sVyJ41X)

**Comment by andrew-pahomov** [comment]
Добрый день. API отвечает на запрос о предоставлении списка карт по адресу http://localhost:9999/api/cards. UI у данного сервиса нет, по адресу http://localhost:9999/ Вы ожидаемого ничего не находите.

**Comment by victoria6991** [comment]
> Добрый день. API отвечает на запрос о предоставлении списка карт по адресу http://localhost:9999/api/cards. UI у данного сервиса нет, по адресу http://localhost:9999/ Вы ожидаемого ничего не находите.

Ой, сглупила, извините!)
